#!/usr/bin/env python3
"""Universal role context — any agent can call this to get role knowledge.

Works with Claude Code, Cursor, Gemini, Codex, Aider, or any custom agent.
No hooks needed. Just call it with a project path.

Usage:
  # Text output (paste into system prompt / context)
  python3 roles/context.py /path/to/project

  # JSON output (for programmatic use)
  python3 roles/context.py /path/to/project --json

  # Specific roles (skip auto-detection)
  python3 roles/context.py /path/to/project --roles backend,frontend,security

  # Pipe into clipboard (macOS)
  python3 roles/context.py /path/to/project | pbcopy

  # Use in Cursor/Codex/Gemini rules file
  python3 roles/context.py . >> .cursorrules
  python3 roles/context.py . >> AGENTS.md
"""

import argparse
import json
import sys
from pathlib import Path
from typing import List, Optional

# Ensure sibling modules are importable
sys.path.insert(0, str(Path(__file__).resolve().parent))

from detect_role import detect_roles, load_role_context


def get_context(
    project_dir: Path,
    roles_dir: Optional[Path] = None,
    config_roles: Optional[List[str]] = None,
    max_roles: int = 4,
) -> str:
    """Get role context as plain text for any agent.

    Args:
        project_dir: Path to the project to analyze
        roles_dir: Path to roles/ directory (defaults to this script's directory)
        config_roles: Override auto-detection with specific roles
        max_roles: Maximum roles to include

    Returns:
        Plain text with active roles + manager principles + knowledge.
        Empty string if no roles detected.
    """
    if roles_dir is None:
        roles_dir = Path(__file__).resolve().parent

    detected = detect_roles(
        project_dir,
        config_roles=config_roles,
        max_roles=max_roles,
    )

    if not detected:
        return ""

    role_names = [r["name"] for r in detected]
    return load_role_context(role_names, roles_dir=roles_dir, max_roles=max_roles)


def get_context_json(
    project_dir: Path,
    roles_dir: Optional[Path] = None,
    config_roles: Optional[List[str]] = None,
    max_roles: int = 4,
) -> str:
    """Get role context as JSON for programmatic use.

    Returns JSON with:
    {
      "roles": [{"name": "backend", "confidence": "high", "signals": [...]}],
      "context": "ACTIVE ROLES: backend, frontend\n..."
    }
    """
    if roles_dir is None:
        roles_dir = Path(__file__).resolve().parent

    detected = detect_roles(
        project_dir,
        config_roles=config_roles,
        max_roles=max_roles,
    )

    role_names = [r["name"] for r in detected]
    context = load_role_context(role_names, roles_dir=roles_dir, max_roles=max_roles) if detected else ""

    return json.dumps({
        "roles": detected,
        "context": context,
    }, indent=2)


def setup_for_project(
    project_dir: Path,
    roles_dir: Optional[Path] = None,
    config_roles: Optional[List[str]] = None,
    max_roles: int = 4,
) -> str:
    """Auto-setup roles for any project — detects tool and writes config.

    Creates the appropriate rules file for whatever AI tool is detected:
    - Claude Code: already handled by hooks (just prints confirmation)
    - Cursor: writes .cursor/rules/roles.md
    - Codex: writes AGENTS.md
    - Gemini: writes .gemini/rules/roles.md
    - Generic: writes AGENTS.md

    Returns path to the created file.
    """
    if roles_dir is None:
        roles_dir = Path(__file__).resolve().parent

    context = get_context(project_dir, roles_dir=roles_dir,
                          config_roles=config_roles, max_roles=max_roles)

    if not context:
        return "No roles detected — no setup needed."

    # Detect which AI tool is in use
    tool = "generic"
    if (project_dir / ".claude").is_dir() or (project_dir / "CLAUDE.md").is_file():
        tool = "claude"
    elif (project_dir / ".cursor").is_dir() or (project_dir / ".cursorrules").is_file():
        tool = "cursor"
    elif (project_dir / ".gemini").is_dir():
        tool = "gemini"

    header = "# Role Context (auto-generated by agent-toolkit)\n# Re-run: python3 roles/context.py --setup\n\n"

    if tool == "claude":
        return "Claude Code detected — roles are injected automatically via hooks. No setup needed."

    elif tool == "cursor":
        rules_dir = project_dir / ".cursor" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        target = rules_dir / "roles.md"
        target.write_text(header + context)
        return str(target)

    elif tool == "gemini":
        rules_dir = project_dir / ".gemini" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        target = rules_dir / "roles.md"
        target.write_text(header + context)
        return str(target)

    else:
        target = project_dir / "AGENTS.md"
        # Append if exists, create if not
        if target.is_file():
            existing = target.read_text()
            if "Role Context" not in existing:
                target.write_text(existing + "\n\n" + header + context)
            else:
                # Replace existing role section
                before = existing.split("# Role Context")[0]
                target.write_text(before + header + context)
        else:
            target.write_text(header + context)
        return str(target)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Get role context for any AI coding agent",
        epilog="Pipe output into your agent's context, rules file, or clipboard.",
    )
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Path to project directory (default: current directory)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output as JSON (for programmatic use)",
    )
    parser.add_argument(
        "--setup",
        action="store_true",
        help="Auto-setup: detect AI tool and write roles config file",
    )
    parser.add_argument(
        "--roles",
        help="Comma-separated role names (skip auto-detection)",
    )
    parser.add_argument(
        "--max-roles",
        type=int,
        default=4,
        help="Maximum roles to include (default: 4)",
    )

    args = parser.parse_args()

    project_dir = Path(args.project_dir).resolve()
    if not project_dir.is_dir():
        print(f"Error: {args.project_dir} is not a directory", file=sys.stderr)
        return 1

    config_roles = args.roles.split(",") if args.roles else None

    if args.setup:
        result = setup_for_project(
            project_dir,
            config_roles=config_roles,
            max_roles=args.max_roles,
        )
        print(f"Setup complete: {result}")
        return 0

    if args.json:
        output = get_context_json(
            project_dir,
            config_roles=config_roles,
            max_roles=args.max_roles,
        )
    else:
        output = get_context(
            project_dir,
            config_roles=config_roles,
            max_roles=args.max_roles,
        )

    if output:
        print(output)
    else:
        print("No roles detected for this project.", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
